# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20190604_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='watch.NeighborHood')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
